apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autopsy.fullname" . }}
  labels:
    {{- include "autopsy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
